services:
  sni5gect:
    image: sni5gect
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sni5gect
    privileged: true
    restart: unless-stopped
    #entrypoint: /sbin/init
    network_mode: host
    volumes:
      - "/dev/:/dev/"
      - "/usr/share/uhd/images:/usr/share/uhd/images"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G
    command: tail -f /dev/null
